// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_EVENTS_H
#define PICOPIXEL_LVGL_UI_EVENTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif


void pp_anim_stop_timelines_for_deleted_tree(lv_obj_t * root);

void action_goto_programs(lv_event_t *e);
void action_goto_program_edit(lv_event_t *e);
void action_goto_settings(lv_event_t *e);
void action_goto_wifi_settings(lv_event_t *e);
void action_goto_main(lv_event_t *e);
void action_start_firing(lv_event_t *e);
void action_pause_firing(lv_event_t *e);
void action_stop_firing(lv_event_t *e);
void action_toggle_language(lv_event_t *e);
void action_programs_graph(lv_event_t *e);
void action_programs_add_step(lv_event_t *e);
void action_programs_sort(lv_event_t *e);
void action_programs_delete_last(lv_event_t *e);
void action_programs_save_as(lv_event_t *e);
void action_programs_save(lv_event_t *e);
void action_programs_delete_row(lv_event_t *e);
void action_programs_row_click(lv_event_t *e);
void action_programs_bind(lv_obj_t *list, lv_obj_t *info_sub);
void action_program_list_new(lv_event_t *e);
void action_program_list_sort(lv_event_t *e);
void action_programs_choose(lv_event_t *e);
void action_program_list_delete(lv_event_t *e);
void action_program_list_start(lv_event_t *e);
void action_program_list_select(lv_event_t *e);
void action_open_keyboard(lv_event_t *e);
void action_close_transient_overlays(void);
void action_block_programs_interaction(uint32_t duration_ms);
void action_debug_dump_overlay_state(const char *origin);
typedef struct {
    uint16_t step;
    uint8_t kind;
} programs_step_kb_ctx_t;

typedef struct {
    uint16_t step;
} programs_step_del_ctx_t;

void action_programs_open_keyboard_step(lv_event_t *e);
void action_programs_delete_step(lv_event_t *e);
void action_program_graph_start(lv_event_t *e);
void action_program_graph_delete(lv_event_t *e);
void action_wifi_choose_network(lv_event_t *e);
void action_wifi_enable_on(lv_event_t *e);
void action_wifi_enable_off(lv_event_t *e);
void action_wifi_toggle(lv_event_t *e);
void action_wifi_open_web_popup(lv_event_t *e);
void action_wifi_clear_logs(lv_event_t *e);
void action_wifi_save_changes(lv_event_t *e);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_EVENTS_H*/
