// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_IMAGES_H
#define PICOPIXEL_LVGL_UI_IMAGES_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifndef EXT_IMG_DESC_T
#define EXT_IMG_DESC_T
typedef struct _ext_img_desc_t {
    const char *name;
    const lv_img_dsc_t *img_dsc;
} ext_img_desc_t;
#endif

extern const lv_img_dsc_t pngwing_com_1_png;
extern const lv_img_dsc_t free_icon_transformer_2804080_png;
extern const lv_img_dsc_t free_icon_thunder_2682835_png;
extern const lv_img_dsc_t music_14073594_png;
extern const lv_img_dsc_t free_icon_electrocardiogram_8011473_png;
extern const lv_img_dsc_t pngwing_com_png;
extern const lv_img_dsc_t free_icon_play_button_arrowhead_27223_png;
extern const lv_img_dsc_t free_icon_right_arrow_271228_png;
extern const lv_img_dsc_t free_icon_speedometer_251043_png;
extern const ext_img_desc_t images[9];


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_IMAGES_H*/
