// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include "lvgl.h"

#ifndef LV_IMG_SIZE_MODE_REAL
#define LV_IMG_SIZE_MODE_REAL 0
#endif

#ifndef lv_img_set_size_mode
#define lv_img_set_size_mode(img, mode) (void)0
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *_2;
    lv_obj_t *_1;
    lv_obj_t *programs_list;
    lv_obj_t *programs;
    lv_obj_t *settings;
    lv_obj_t *wifi_settings;
    lv_obj_t *program_graph;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID__2 = 1,
    SCREEN_ID__1 = 2,
    SCREEN_ID_PROGRAMS_LIST = 3,
    SCREEN_ID_PROGRAMS = 4,
    SCREEN_ID_SETTINGS = 5,
    SCREEN_ID_WIFI_SETTINGS = 6,
    SCREEN_ID_PROGRAM_GRAPH = 7,
};

void create_screen__2();
void tick_screen__2();
void delete_screen__2();
void create_screen__1();
void tick_screen__1();
void delete_screen__1();
void create_screen_programs_list();
void tick_screen_programs_list();
void delete_screen_programs_list();
void screen_programs_list_refresh();
void create_screen_programs();
void tick_screen_programs();
void delete_screen_programs();
void screen_programs_refresh_rows();
void screen_programs_scroll_to_last(void);
void create_screen_settings();
void tick_screen_settings();
void delete_screen_settings();
void create_screen_wifi_settings();
void tick_screen_wifi_settings();
void delete_screen_wifi_settings();
void create_screen_program_graph();
void tick_screen_program_graph();
void delete_screen_program_graph();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();

void ui_s3_post_scale(enum ScreensEnum screenId);


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
