// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_H
#define PICOPIXEL_LVGL_UI_H

#include "lvgl.h"

#include "screens.h"

#ifdef __cplusplus
extern "C" {
#endif

void ui_init();
void ui_tick();
void ui_debug_settings_freeze_reportf(const char *run_id, const char *hypothesis_id, const char *location, const char *fmt, ...);
bool ui_is_navigation_active(void);
enum ScreensEnum ui_get_current_screen_id(void);
bool ui_lvgl_draw_buffer_memory_check(const char *phase);

void loadScreen(enum ScreensEnum screenId);
void requestScreen(enum ScreensEnum screenId);

bool ui_is_english();
void ui_request_toggle_language();

uint16_t ui_get_display_sleep_minutes();
void ui_set_display_sleep_minutes(uint16_t minutes);
void ui_notify_user_activity();

typedef enum {
    UI_DATE_FORMAT_DDMMYYYY = 0,
    UI_DATE_FORMAT_MMDDYYYY = 1,
    UI_DATE_FORMAT_YYYYMMDD = 2,
} ui_date_format_t;

typedef enum {
    UI_TIME_FORMAT_24H = 0,
    UI_TIME_FORMAT_12H = 1,
} ui_time_format_t;

typedef enum {
    UI_TEMP_UNIT_C = 0,
    UI_TEMP_UNIT_F = 1,
} ui_temp_unit_t;

ui_date_format_t ui_get_date_format();
void ui_set_date_format(ui_date_format_t fmt);

ui_time_format_t ui_get_time_format();
void ui_set_time_format(ui_time_format_t fmt);

ui_temp_unit_t ui_get_temp_unit();
void ui_set_temp_unit(ui_temp_unit_t unit);

void ui_set_selected_program_name(const char *name);
const char *ui_get_selected_program_name();
void ui_set_selected_program_steps_total(uint16_t steps);
uint16_t ui_get_selected_program_steps_total();

void ui_set_selected_program_id(uint8_t id);
uint8_t ui_get_selected_program_id();

void ui_set_program_steps_total(uint8_t id, uint16_t steps);
uint16_t ui_get_program_steps_total(uint8_t id);
uint8_t ui_get_program_count();
uint8_t ui_get_program_capacity();
bool ui_is_programs_full();
bool ui_delete_program(uint8_t id);
const char *ui_get_program_name(uint8_t id);
void ui_set_program_name(uint8_t id, const char *name);
uint8_t ui_add_program(const char *name, uint16_t steps_total);
void ui_programs_persist_save();

void ui_set_program_total_time_s(uint8_t id, uint32_t sec);
uint32_t ui_get_program_total_time_s(uint8_t id);

#define UI_MAX_PROGRAMS 20
#define UI_MAX_STEPS 50

typedef struct {
    int16_t temp_c;
    uint16_t rate_c_per_h_x10;
    uint32_t hold_s;
} ui_step_t;

void ui_get_program_steps_batch(uint8_t id, ui_step_t *out_steps, uint16_t max_count);

typedef struct {
    char name[96];
    uint16_t steps_total;
    uint32_t total_time_s;
} ui_program_info_t;

void ui_get_programs_batch(ui_program_info_t *out_programs, uint8_t max_count);

void ui_set_program_step(uint8_t id, uint16_t step_idx, int16_t temp_c, uint16_t rate_c_per_h_x10, uint32_t hold_s);
int16_t ui_get_program_step_temp(uint8_t id, uint16_t step_idx);
uint16_t ui_get_program_step_rate_c_per_h_x10(uint8_t id, uint16_t step_idx);
uint32_t ui_get_program_step_hold_s(uint8_t id, uint16_t step_idx);

bool ui_program_add_step(uint8_t id);
bool ui_program_delete_step(uint8_t id, uint16_t step_idx);

void ui_set_selected_program_total_time_s(uint32_t sec);
uint32_t ui_get_selected_program_total_time_s();
void ui_set_selected_program_max_temp_c(uint16_t temp);
uint16_t ui_get_selected_program_max_temp_c();
void ui_set_selected_program_breakpoints(const int16_t *temps, const uint32_t *times, uint8_t count);
uint8_t ui_get_selected_program_breakpoint_count();
int16_t ui_get_selected_program_breakpoint_temp(uint8_t idx);
uint32_t ui_get_selected_program_breakpoint_time_s(uint8_t idx);

#ifdef __cplusplus
}
#endif

#endif // PICOPIXEL_LVGL_UI_H
