// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;
uint32_t active_theme_index = 0;

void create_screen__2() {
    lv_obj_t *obj = lv_obj_create(0);
    objects._2 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 800, 480);
        lv_obj_set_style_bg_opa(obj, 146, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(0xff090c10), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // button_2
            lv_obj_t *obj = lv_btn_create(parent_obj);
            lv_obj_set_pos(obj, 680, 250);
            lv_obj_set_size(obj, 110, 110);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff421212), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_outline_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xffff3b30), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 168, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_2_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_label_set_text(obj, "");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // image_2
            lv_obj_t *obj = lv_img_create(parent_obj);
            lv_obj_set_pos(obj, 466, 290);
            lv_obj_set_size(obj, 24, 24);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &free_icon_play_button_arrowhead_27223_png);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
        }
        {
            // panel_3 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 10, 371);
            lv_obj_set_size(obj, 780, 99);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_10
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.current_label = obj;
                    lv_obj_set_pos(obj, 241, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Струм");
                }
                {
                    // image_5
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_thunder_2682835_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
                {
                    // label_26
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 55, 60);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "230 V");
                }
                {
                    // label_27
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 241, 59);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "2.4 A");
                }
                {
                    // label_29
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.energy_label = obj;
                    lv_obj_set_pos(obj, 631, 58);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "1.25 kWh");
                }
                {
                    // label_8
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 14, 11);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Електрична мережа");
                }
                {
                    // label_12
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 631, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Споживання");
                }
                {
                    // label_25
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.voltage_label = obj;
                    lv_obj_set_pos(obj, 55, 60);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "230 V");
                }
                {
                    // image_8
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 590, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_transformer_2804080_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
                {
                    // image_6
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 200, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_electrocardiogram_8011473_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
                {
                    // image_7
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 395, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_speedometer_251043_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
                {
                    // label_9
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 55, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Напруга");
                }
                {
                    // label_11
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.power_label = obj;
                    lv_obj_set_pos(obj, 436, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Потужність");
                }
                {
                    // label_28
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 436, 59);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "552 W");
                }
            }
        }
        {
            // label_13
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 64, 14);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "KilnPro");
        }
        {
            // panel_5 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 724, 290);
            lv_obj_set_size(obj, 24, 24);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xffff3b30), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // panel_6 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 664, 16);
            lv_obj_set_size(obj, 45, 32);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_19
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 10, 6);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "UA");
                }
            }
        }
        {
            // label_15
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 417, 324);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Пропустити");
        }
        {
            // panel_2 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 405, 63);
            lv_obj_set_size(obj, 385, 177);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 224, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_23
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.step_label = obj;
                    lv_obj_set_pos(obj, 13, 91);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Крок");
                }
                {
                    // label_21
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 13, 12);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Вибрана програма");
                }
                {
                    // bar_2
                    lv_obj_t *obj = lv_bar_create(parent_obj);
                    lv_obj_set_pos(obj, 13, 127);
                    lv_obj_set_size(obj, 358, 11);
                    lv_bar_set_range(obj, 1, 10);
                    lv_bar_set_value(obj, 2, LV_ANIM_OFF);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff00b761), LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
                {
                    // label_24
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 344, 89);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "2/10");
                }
                {
                    // label_22
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.program_name = obj;
                    lv_obj_set_pos(obj, 13, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Нова програма 3");
                }
                {
                    // image_9
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 340, 37);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_right_arrow_271228_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
            }
        }
        {
            // image_3
            lv_obj_t *obj = lv_img_create(parent_obj);
            lv_obj_set_pos(obj, 588, 275);
            lv_obj_set_size(obj, 55, 55);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &music_14073594_png);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_zoom(obj, 220);
        }
        {
            // button_3
            lv_obj_t *obj = lv_btn_create(parent_obj);
            lv_obj_set_pos(obj, 560, 250);
            lv_obj_set_size(obj, 110, 110);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_3_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_label_set_text(obj, "");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // image_4
            lv_obj_t *obj = lv_img_create(parent_obj);
            lv_obj_set_pos(obj, 745, 16);
            lv_obj_set_size(obj, 32, 32);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &pngwing_com_png);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
        }
        {
            // image_1
            lv_obj_t *obj = lv_img_create(parent_obj);
            lv_obj_set_pos(obj, 596, 16);
            lv_obj_set_size(obj, 32, 32);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &pngwing_com_1_png);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
        }
        {
            // panel_1 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 10, 60);
            lv_obj_set_size(obj, 385, 300);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 206, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_3
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.current_temp = obj;
                    lv_obj_set_pos(obj, 15, 80);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d08108ddeb9, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "27,5");
                }
                {
                    // label_16
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 232, 94);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d008712449e, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "°C");
                }
                {
                    // bar_1
                    lv_obj_t *obj = lv_bar_create(parent_obj);
                    lv_obj_set_pos(obj, 16, 271);
                    lv_obj_set_size(obj, 354, 10);
                    lv_bar_set_range(obj, 0, 100);
                    lv_bar_set_value(obj, 50, LV_ANIM_OFF);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff00b761), LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
                {
                    // label_6
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 230);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "27,5 ° С");
                }
                {
                    // panel_4 (scrollable panel)
                    lv_obj_t *obj = lv_obj_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 15);
                    lv_obj_set_size(obj, 148, 30);
                    lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_width(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_pad(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    {
                        lv_obj_t *parent_obj = obj;
                        {
                            // label_1
                            lv_obj_t *obj = lv_label_create(parent_obj);
                            objects.state_label = obj;
                            lv_obj_set_pos(obj, 23, 6);
                            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d011b20aec8, LV_PART_MAIN | LV_STATE_DEFAULT);
                            lv_obj_set_style_text_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                            lv_label_set_text(obj, "ОЧІКУВАННЯ");
                        }
                    }
                }
                {
                    // label_2
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 55);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Поточна температура");
                }
                {
                    // label_5
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 203, 210);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Швидкість нагрівання");
                }
                {
                    // label_20
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 261, 241);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "° С/год");
                }
                {
                    // label_4
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 210);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Цільова температура");
                }
                {
                    // label_7
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.target_temp = obj;
                    lv_obj_set_pos(obj, 204, 230);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "100 ");
                }
            }
        }
        {
            // button_1
            lv_obj_t *obj = lv_btn_create(parent_obj);
            lv_obj_set_pos(obj, 405, 250);
            lv_obj_set_size(obj, 145, 110);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xffb77100), LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_1_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_label_set_text(obj, "");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // label_18
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 715, 324);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Стоп");
        }
        {
            // label_17
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 589, 324);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Пауза");
        }
        {
            // label_14
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.time_label = obj;
            lv_obj_set_pos(obj, 418, 25);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0941ee88b1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "19:25 19.05.2026");
        }
        {
            // panel_7 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 25, 13);
            lv_obj_set_size(obj, 32, 32);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
    }

    tick_screen__2();
}

void tick_screen__2() {
}


void create_screen__1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects._1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 800, 480);
        lv_obj_set_style_bg_opa(obj, 146, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(0xff090c10), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // label_30_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 64, 14);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "KilnPro");
        }
        {
            // image_10
            lv_obj_t *obj = lv_img_create(parent_obj);
            lv_obj_set_pos(obj, 745, 16);
            lv_obj_set_size(obj, 32, 32);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &pngwing_com_png);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
        }
        {
            // panel_8_1 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 10, 60);
            lv_obj_set_size(obj, 385, 300);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 206, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_30_3
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 232, 94);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d008712449e, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "°C");
                }
                {
                    // bar_3
                    lv_obj_t *obj = lv_bar_create(parent_obj);
                    lv_obj_set_pos(obj, 16, 271);
                    lv_obj_set_size(obj, 354, 10);
                    lv_bar_set_range(obj, 0, 100);
                    lv_bar_set_value(obj, 50, LV_ANIM_OFF);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff00b761), LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
                {
                    // label_30_6
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 204, 230);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "100 ");
                }
                {
                    // panel_8 (scrollable panel)
                    lv_obj_t *obj = lv_obj_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 15);
                    lv_obj_set_size(obj, 148, 30);
                    lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_width(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_outline_pad(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    {
                        lv_obj_t *parent_obj = obj;
                        {
                            // label_30_17
                            lv_obj_t *obj = lv_label_create(parent_obj);
                            lv_obj_set_pos(obj, 23, 6);
                            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d011b20aec8, LV_PART_MAIN | LV_STATE_DEFAULT);
                            lv_obj_set_style_text_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                            lv_label_set_text(obj, "ОЧІКУВАННЯ");
                        }
                    }
                }
                {
                    // label_30_12
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 203, 210);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Швидкість нагрівання");
                }
                {
                    // label_30_13
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 261, 241);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "° С/год");
                }
                {
                    // label_30_20
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 210);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Цільова температура");
                }
                {
                    // label_30_21
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 80);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d08108ddeb9, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "27,5");
                }
                {
                    // label_30_22
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 55);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Поточна температура");
                }
                {
                    // label_30_23
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 230);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "27,5 ° С");
                }
            }
        }
        {
            // button_4
            lv_obj_t *obj = lv_btn_create(parent_obj);
            lv_obj_set_pos(obj, 405, 250);
            lv_obj_set_size(obj, 190, 110);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_4_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_label_set_text(obj, "");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // label_30_10
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 418, 25);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0941ee88b1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_decor(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "19:25 19.05.2026");
        }
        {
            // image_10_4
            lv_obj_t *obj = lv_img_create(parent_obj);
            lv_obj_set_pos(obj, 488, 290);
            lv_obj_set_size(obj, 24, 24);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &free_icon_play_button_arrowhead_27223_png);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
        }
        {
            // button_4_1
            lv_obj_t *obj = lv_btn_create(parent_obj);
            lv_obj_set_pos(obj, 605, 250);
            lv_obj_set_size(obj, 185, 110);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_4_1_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_label_set_text(obj, "");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // panel_8_2 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 405, 63);
            lv_obj_set_size(obj, 385, 177);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 224, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_30_8
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 13, 91);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Крок");
                }
                {
                    // bar_3_1
                    lv_obj_t *obj = lv_bar_create(parent_obj);
                    lv_obj_set_pos(obj, 13, 127);
                    lv_obj_set_size(obj, 358, 11);
                    lv_bar_set_range(obj, 1, 10);
                    lv_bar_set_value(obj, 2, LV_ANIM_OFF);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_color(obj, lv_color_hex(0xff00b761), LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_radius(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
                    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                }
                {
                    // label_30_14
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 13, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d0337447350, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Нова програма 3");
                }
                {
                    // label_30_18
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 13, 12);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Вибрана програма");
                }
                {
                    // label_30_19
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 344, 89);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "2/10");
                }
                {
                    // image_10_6
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 340, 37);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_right_arrow_271228_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
            }
        }
        {
            // panel_8_3 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 25, 13);
            lv_obj_set_size(obj, 32, 32);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // panel_8_4 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 664, 16);
            lv_obj_set_size(obj, 45, 32);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_30_25
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 10, 6);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "UA");
                }
            }
        }
        {
            // image_10_5
            lv_obj_t *obj = lv_img_create(parent_obj);
            lv_obj_set_pos(obj, 596, 16);
            lv_obj_set_size(obj, 32, 32);
            lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_img_set_src(obj, &pngwing_com_1_png);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_CLICKABLE);
        }
        {
            // panel_8_5 (scrollable panel)
            lv_obj_t *obj = lv_obj_create(parent_obj);
            lv_obj_set_pos(obj, 10, 371);
            lv_obj_set_size(obj, 780, 99);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff1c2538), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(0xff0e131f), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // label_30
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 241, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Струм");
                }
                {
                    // label_30_2
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 55, 60);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "230 V");
                }
                {
                    // label_30_4
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 55, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Напруга");
                }
                {
                    // label_30_5
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 436, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Потужність");
                }
                {
                    // label_30_7
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 241, 59);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "2.4 A");
                }
                {
                    // image_10_1
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 15, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_thunder_2682835_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
                {
                    // image_10_2
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 200, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_electrocardiogram_8011473_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
                {
                    // image_10_3
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 395, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_speedometer_251043_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
                {
                    // label_30_9
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 55, 60);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "230 V");
                }
                {
                    // label_30_11
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 436, 59);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "552 W");
                }
                {
                    // label_30_15
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 14, 11);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xff7a8b9e), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Електрична мережа");
                }
                {
                    // label_30_16
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 631, 58);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "1.25 kWh");
                }
                {
                    // label_30_24
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    lv_obj_set_pos(obj, 631, 38);
                    lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
                    lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d015637c7d0, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_label_set_text(obj, "Споживання");
                }
                {
                    // image_10_7
                    lv_obj_t *obj = lv_img_create(parent_obj);
                    lv_obj_set_pos(obj, 590, 43);
                    lv_obj_set_size(obj, 32, 32);
                    lv_obj_set_style_img_recolor_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_obj_set_style_img_recolor(obj, lv_color_hex(0xff00b761), LV_PART_MAIN | LV_STATE_DEFAULT);
                    lv_img_set_src(obj, &free_icon_transformer_2804080_png);
                    lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
                }
            }
        }
        {
            // label_30_26
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 654, 324);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xffffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Програми");
        }
        {
            // label_30_27
            lv_obj_t *obj = lv_label_create(parent_obj);
            lv_obj_set_pos(obj, 441, 324);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_4305a60a491c803d80080d05cbb3cac2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Старт випалу");
        }
    }

    tick_screen__1();
}

void tick_screen__1() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen__2,
    tick_screen__1,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen__2() {
    if (objects._2 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects._2);
        lv_obj_del(objects._2);
    }
    objects._2 = 0;
}

void delete_screen__1() {
    if (objects._1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects._1);
        lv_obj_del(objects._1);
    }
    objects._1 = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen__2,
    delete_screen__1,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen__2();
    create_screen__1();
}
