// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl/lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *_2;
    lv_obj_t *_1;
    lv_obj_t *current_temp;
    lv_obj_t *target_temp;
    lv_obj_t *step_label;
    lv_obj_t *program_name;
    lv_obj_t *state_label;
    lv_obj_t *time_label;
    lv_obj_t *power_label;
    lv_obj_t *voltage_label;
    lv_obj_t *current_label;
    lv_obj_t *energy_label;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID__2 = 1,
    SCREEN_ID__1 = 2,
};

void create_screen__2();
void tick_screen__2();
void delete_screen__2();
void create_screen__1();
void tick_screen__1();
void delete_screen__1();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
