// Generated by PicoPixel.io — https://picopixel.io
#include "sdkconfig.h"
#include "ui.h"
#include "screens.h"
#include "images.h"
#include "actions.h"
#include "vars.h"

#include <string.h>

static int16_t currentScreen = -1;

static lv_obj_t *getLvglObjectFromIndex(int32_t index) {
    if (index == -1) {
        return 0;
    }
    return ((lv_obj_t **)&objects)[index];
}

static void disable_scrolling_recursive(lv_obj_t *obj) {
    if (!obj) return;
    lv_obj_remove_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scroll_dir(obj, LV_DIR_NONE);
    lv_obj_set_scrollbar_mode(obj, LV_SCROLLBAR_MODE_OFF);
    uint32_t i = 0;
    while (true) {
        lv_obj_t *child = lv_obj_get_child(obj, i);
        if (!child) break;
        disable_scrolling_recursive(child);
        i++;
    }
}

static lv_coord_t mul_zoom(lv_coord_t v, int32_t zoom_256) {
    return (lv_coord_t)(((int64_t)v * (int64_t)zoom_256) / 256);
}

static void rescale_obj_tree(lv_obj_t *obj, int32_t zoom_256, lv_coord_t add_x, lv_coord_t add_y) {
    if (!obj) return;

    disable_scrolling_recursive(obj);

    const lv_coord_t old_x = lv_obj_get_x(obj);
    const lv_coord_t old_y = lv_obj_get_y(obj);
    lv_obj_set_pos(obj, (lv_coord_t)(add_x + mul_zoom(old_x, zoom_256)), (lv_coord_t)(add_y + mul_zoom(old_y, zoom_256)));

    const lv_coord_t sw = lv_obj_get_style_width(obj, LV_PART_MAIN);
    const lv_coord_t sh = lv_obj_get_style_height(obj, LV_PART_MAIN);
    if (sw >= 0) {
        const lv_coord_t nw = mul_zoom(sw, zoom_256);
        lv_obj_set_width(obj, (nw <= 0) ? 1 : nw);
    }
    if (sh >= 0) {
        const lv_coord_t nh = mul_zoom(sh, zoom_256);
        lv_obj_set_height(obj, (nh <= 0) ? 1 : nh);
    }

    uint32_t i = 0;
    while (true) {
        lv_obj_t *child = lv_obj_get_child(obj, i);
        if (!child) break;
        rescale_obj_tree(child, zoom_256, 0, 0);
        i++;
    }
}

static void scale_screen_to_display_if_needed(lv_obj_t *screen) {
    if (!screen) return;

    const int32_t design_w = 800;
    const int32_t design_h = 480;

    disable_scrolling_recursive(screen);
    if (lv_obj_has_flag(screen, LV_OBJ_FLAG_USER_2)) return;
    lv_obj_add_flag(screen, LV_OBJ_FLAG_USER_2);

    lv_disp_t *disp = lv_disp_get_default();
    if (!disp) return;

    const int32_t hor = (int32_t)lv_disp_get_hor_res(disp);
    const int32_t ver = (int32_t)lv_disp_get_ver_res(disp);
    if (hor <= 0 || ver <= 0) return;

    lv_obj_set_size(screen, hor, ver);

    const int32_t zoom_w = (hor * 256) / design_w;
    const int32_t zoom_h = (ver * 256) / design_h;
    const int32_t zoom = (zoom_w < zoom_h) ? zoom_w : zoom_h;
    if (zoom <= 0 || zoom >= 256) {
        uint32_t i = 0;
        while (true) {
            lv_obj_t *child = lv_obj_get_child(screen, i);
            if (!child) break;
            disable_scrolling_recursive(child);
            i++;
        }
        return;
    }

    const int32_t scaled_w = (design_w * zoom) / 256;
    const int32_t scaled_h = (design_h * zoom) / 256;
    const int32_t x_off = (hor - scaled_w) / 2;
    const int32_t y_off = (ver - scaled_h) / 2;

    uint32_t i = 0;
    while (true) {
        lv_obj_t *child = lv_obj_get_child(screen, i);
        if (!child) break;
        rescale_obj_tree(child, zoom, (lv_coord_t)x_off, (lv_coord_t)y_off);
        i++;
    }
}

void loadScreen(enum ScreensEnum screenId) {
    currentScreen = screenId - 1;
    lv_obj_t *screen = getLvglObjectFromIndex(currentScreen);
    lv_scr_load_anim(screen, LV_SCR_LOAD_ANIM_FADE_IN, 200, 0, false);
}

void ui_init() {
    create_screens();
    scale_screen_to_display_if_needed(objects._2);
    scale_screen_to_display_if_needed(objects._1);
    loadScreen(SCREEN_ID__2);
}

void ui_tick() {
    tick_screen(currentScreen);
}
