// Generated by PicoPixel.io — https://picopixel.io
/**
 * @file fonts.c
 * @brief Custom font lookup for LVGL UI
 *
 * Each font .c file is compiled separately.
 */

#include "fonts.h"
#include <string.h>

const lv_font_t* ui_get_font_by_name(const char* name) {
    if (name == NULL) return NULL;
    if (strcmp(name, "font_4305a60a491c803d80080d00155e1160") == 0) return &font_4305a60a491c803d80080d00155e1160;
    if (strcmp(name, "font_4305a60a491c803d80080d008712449e") == 0) return &font_4305a60a491c803d80080d008712449e;
    if (strcmp(name, "font_4305a60a491c803d80080d011b20aec8") == 0) return &font_4305a60a491c803d80080d011b20aec8;
    if (strcmp(name, "font_4305a60a491c803d80080d015637c7d0") == 0) return &font_4305a60a491c803d80080d015637c7d0;
    if (strcmp(name, "font_4305a60a491c803d80080d0276f8a0f7") == 0) return &font_4305a60a491c803d80080d0276f8a0f7;
    if (strcmp(name, "font_4305a60a491c803d80080d0337447350") == 0) return &font_4305a60a491c803d80080d0337447350;
    if (strcmp(name, "font_4305a60a491c803d80080d05cbb3cac2") == 0) return &font_4305a60a491c803d80080d05cbb3cac2;
    if (strcmp(name, "font_4305a60a491c803d80080d08108ddeb9") == 0) return &font_4305a60a491c803d80080d08108ddeb9;
    if (strcmp(name, "font_4305a60a491c803d80080d0941ee88b1") == 0) return &font_4305a60a491c803d80080d0941ee88b1;
    return NULL;
}
