// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_FONTS_H
#define PICOPIXEL_LVGL_UI_FONTS_H

#include <lvgl/lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Custom font declarations (externally visible const structs, no init needed) */
extern const lv_font_t font_4305a60a491c803d80080d00155e1160;
extern const lv_font_t font_4305a60a491c803d80080d008712449e;
extern const lv_font_t font_4305a60a491c803d80080d011b20aec8;
extern const lv_font_t font_4305a60a491c803d80080d015637c7d0;
extern const lv_font_t font_4305a60a491c803d80080d0276f8a0f7;
extern const lv_font_t font_4305a60a491c803d80080d0337447350;
extern const lv_font_t font_4305a60a491c803d80080d05cbb3cac2;
extern const lv_font_t font_4305a60a491c803d80080d08108ddeb9;
extern const lv_font_t font_4305a60a491c803d80080d0941ee88b1;

/* Get a custom font by name, returns NULL if not found */
const lv_font_t* ui_get_font_by_name(const char* name);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_FONTS_H*/
